// Auto-generated by depot-test-generator. Do not edit manually.
// Source fixtures: crates/depot-core/testing_data

use serde_json::Value;

// Fixture: config/01_config_parsing.json
#[test]
fn config_01_config_parsing_minimal_config() {
    // Fixture: config/01_config_parsing.json | Case: "minimal config"
    let input: Value = serde_json::from_str(r#"{"toml":"[server]\nbind = \"127.0.0.1:3000\"\n"}"#)
        .expect("parse input");
    let expected: Value =
        serde_json::from_str(r#"{"bind":"127.0.0.1:3000","storage_backend":"fs"}"#)
            .expect("parse expected");
    // This test case expects success.
    assert!(
        expected.is_object(),
        "expected must be a JSON object: {}",
        "minimal config"
    );
    assert!(
        !expected.as_object().unwrap().is_empty(),
        "expected must not be empty for success case: {}",
        "minimal config"
    );
    let _ = input;
}

#[test]
fn config_01_config_parsing_full_config() {
    // Fixture: config/01_config_parsing.json | Case: "full config"
    let input: Value = serde_json::from_str(r#"{"toml":"[server]\nbind = \"0.0.0.0:9090\"\n\n[storage]\nbackend = \"s3\"\n\n[storage.s3]\nbucket = \"my-bucket\"\nregion = \"us-west-2\"\n\n[upstream.pypi]\nenabled = true\nurl = \"https://pypi.org\"\n\n[policies]\nblock_unlicensed = true\nmax_vuln_severity = \"high\"\nallowed_licenses = [\"MIT\", \"Apache-2.0\"]\n\n[auth]\nenabled = true\ntokens = [\"secret-token\"]\n"}"#).expect("parse input");
    let expected: Value = serde_json::from_str(r#"{"auth_enabled":true,"bind":"0.0.0.0:9090","block_unlicensed":true,"s3_bucket":"my-bucket","storage_backend":"s3"}"#).expect("parse expected");
    // This test case expects success.
    assert!(
        expected.is_object(),
        "expected must be a JSON object: {}",
        "full config"
    );
    assert!(
        !expected.as_object().unwrap().is_empty(),
        "expected must not be empty for success case: {}",
        "full config"
    );
    let _ = input;
}

#[test]
fn config_01_config_parsing_empty_config_uses_defaults() {
    // Fixture: config/01_config_parsing.json | Case: "empty config uses defaults"
    let input: Value = serde_json::from_str(r#"{"toml":""}"#).expect("parse input");
    let expected: Value = serde_json::from_str(r#"{"bind":"0.0.0.0:8080","storage_backend":"fs"}"#)
        .expect("parse expected");
    // This test case expects success.
    assert!(
        expected.is_object(),
        "expected must be a JSON object: {}",
        "empty config uses defaults"
    );
    assert!(
        !expected.as_object().unwrap().is_empty(),
        "expected must not be empty for success case: {}",
        "empty config uses defaults"
    );
    let _ = input;
}

#[test]
fn config_01_config_parsing_invalid_toml() {
    // Fixture: config/01_config_parsing.json | Case: "invalid toml"
    let input: Value =
        serde_json::from_str(r#"{"toml":"[server\nbind = oops"}"#).expect("parse input");
    let expected: Value = serde_json::from_str(r#"{}"#).expect("parse expected");
    let error_substring = "toml parse error";
    // This test case expects an error.
    assert!(
        !expected.as_object().is_some_and(|obj| obj.is_empty()) || !error_substring.is_empty(),
        "error case must have non-empty error substring or non-empty expected: {} ({})",
        error_substring,
        "invalid toml"
    );
    // Verify fixture is loadable and error field is present.
    assert!(
        !error_substring.is_empty(),
        "error substring should not be empty for error case: {}",
        "invalid toml"
    );
    let _ = (input, expected);
}

// Fixture: integrity/01_blake3_vectors.json
#[test]
fn integrity_01_blake3_vectors_empty_input() {
    // Fixture: integrity/01_blake3_vectors.json | Case: "empty input"
    let input: Value = serde_json::from_str(r#"{"data":""}"#).expect("parse input");
    let expected: Value = serde_json::from_str(
        r#"{"blake3":"af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262"}"#,
    )
    .expect("parse expected");
    // This test case expects success.
    assert!(
        expected.is_object(),
        "expected must be a JSON object: {}",
        "empty input"
    );
    assert!(
        !expected.as_object().unwrap().is_empty(),
        "expected must not be empty for success case: {}",
        "empty input"
    );
    let _ = input;
}

#[test]
fn integrity_01_blake3_vectors_hello_depot() {
    // Fixture: integrity/01_blake3_vectors.json | Case: "hello depot"
    let input: Value = serde_json::from_str(r#"{"data":"hello depot"}"#).expect("parse input");
    let expected: Value = serde_json::from_str(r#"{"blake3":null}"#).expect("parse expected");
    // This test case expects success.
    assert!(
        expected.is_object(),
        "expected must be a JSON object: {}",
        "hello depot"
    );
    assert!(
        !expected.as_object().unwrap().is_empty(),
        "expected must not be empty for success case: {}",
        "hello depot"
    );
    let _ = input;
}

#[test]
fn integrity_01_blake3_vectors_binary_like_data() {
    // Fixture: integrity/01_blake3_vectors.json | Case: "binary-like data"
    let input: Value =
        serde_json::from_str(r#"{"data":"\u0000\u0001\u0002\u0003"}"#).expect("parse input");
    let expected: Value = serde_json::from_str(r#"{"blake3":null}"#).expect("parse expected");
    // This test case expects success.
    assert!(
        expected.is_object(),
        "expected must be a JSON object: {}",
        "binary-like data"
    );
    assert!(
        !expected.as_object().unwrap().is_empty(),
        "expected must not be empty for success case: {}",
        "binary-like data"
    );
    let _ = input;
}

// Fixture: lockfile/01_roundtrip.json
#[test]
fn lockfile_01_roundtrip_minimal_lock_file() {
    // Fixture: lockfile/01_roundtrip.json | Case: "minimal lock file"
    let input: Value = serde_json::from_str(r#"{"toml":"[metadata]\nschema_version = 1\ngenerated_at = \"2026-04-19T10:30:00Z\"\ndepot_version = \"0.1.0\"\n"}"#).expect("parse input");
    let expected: Value =
        serde_json::from_str(r#"{"depot_version":"0.1.0","package_count":0,"schema_version":1}"#)
            .expect("parse expected");
    // This test case expects success.
    assert!(
        expected.is_object(),
        "expected must be a JSON object: {}",
        "minimal lock file"
    );
    assert!(
        !expected.as_object().unwrap().is_empty(),
        "expected must not be empty for success case: {}",
        "minimal lock file"
    );
    let _ = input;
}

#[test]
fn lockfile_01_roundtrip_lock_file_with_one_package() {
    // Fixture: lockfile/01_roundtrip.json | Case: "lock file with one package"
    let input: Value = serde_json::from_str(r#"{"toml":"[metadata]\nschema_version = 1\ngenerated_at = \"2026-04-19T10:30:00Z\"\ndepot_version = \"0.1.0\"\n\n[[packages]]\necosystem = \"pypi\"\nname = \"requests\"\nversion = \"2.31.0\"\nresolved_from = \"https://pypi.org\"\npinned = true\n\n[[packages.artifacts]]\nfilename = \"requests-2.31.0.tar.gz\"\nblake3 = \"abcdef1234567890\"\nsize = 110293\n"}"#).expect("parse input");
    let expected: Value = serde_json::from_str(r#"{"depot_version":"0.1.0","first_package_ecosystem":"pypi","first_package_name":"requests","package_count":1,"schema_version":1}"#).expect("parse expected");
    // This test case expects success.
    assert!(
        expected.is_object(),
        "expected must be a JSON object: {}",
        "lock file with one package"
    );
    assert!(
        !expected.as_object().unwrap().is_empty(),
        "expected must not be empty for success case: {}",
        "lock file with one package"
    );
    let _ = input;
}

#[test]
fn lockfile_01_roundtrip_lock_file_with_multiple_ecosystems() {
    // Fixture: lockfile/01_roundtrip.json | Case: "lock file with multiple ecosystems"
    let input: Value = serde_json::from_str(r#"{"toml":"[metadata]\nschema_version = 1\ngenerated_at = \"2026-04-19T10:30:00Z\"\ndepot_version = \"0.1.0\"\n\n[[packages]]\necosystem = \"pypi\"\nname = \"requests\"\nversion = \"2.31.0\"\nresolved_from = \"https://pypi.org\"\n\n[[packages.artifacts]]\nfilename = \"requests-2.31.0.tar.gz\"\nblake3 = \"aaa\"\nsize = 100\n\n[[packages]]\necosystem = \"npm\"\nname = \"lodash\"\nversion = \"4.17.21\"\nresolved_from = \"https://registry.npmjs.org\"\n\n[[packages.artifacts]]\nfilename = \"lodash-4.17.21.tgz\"\nblake3 = \"bbb\"\nsize = 200\n"}"#).expect("parse input");
    let expected: Value =
        serde_json::from_str(r#"{"package_count":2,"schema_version":1}"#).expect("parse expected");
    // This test case expects success.
    assert!(
        expected.is_object(),
        "expected must be a JSON object: {}",
        "lock file with multiple ecosystems"
    );
    assert!(
        !expected.as_object().unwrap().is_empty(),
        "expected must not be empty for success case: {}",
        "lock file with multiple ecosystems"
    );
    let _ = input;
}

// Fixture: package/01_pypi_normalization.json
#[test]
fn package_01_pypi_normalization_pypi_underscore_to_hyphen() {
    // Fixture: package/01_pypi_normalization.json | Case: "pypi underscore to hyphen"
    let input: Value =
        serde_json::from_str(r#"{"ecosystem":"pypi","name":"my_package"}"#).expect("parse input");
    let expected: Value =
        serde_json::from_str(r#"{"normalized":"my-package"}"#).expect("parse expected");
    // This test case expects success.
    assert!(
        expected.is_object(),
        "expected must be a JSON object: {}",
        "pypi underscore to hyphen"
    );
    assert!(
        !expected.as_object().unwrap().is_empty(),
        "expected must not be empty for success case: {}",
        "pypi underscore to hyphen"
    );
    let _ = input;
}

#[test]
fn package_01_pypi_normalization_pypi_uppercase_to_lowercase() {
    // Fixture: package/01_pypi_normalization.json | Case: "pypi uppercase to lowercase"
    let input: Value =
        serde_json::from_str(r#"{"ecosystem":"pypi","name":"MyPackage"}"#).expect("parse input");
    let expected: Value =
        serde_json::from_str(r#"{"normalized":"mypackage"}"#).expect("parse expected");
    // This test case expects success.
    assert!(
        expected.is_object(),
        "expected must be a JSON object: {}",
        "pypi uppercase to lowercase"
    );
    assert!(
        !expected.as_object().unwrap().is_empty(),
        "expected must not be empty for success case: {}",
        "pypi uppercase to lowercase"
    );
    let _ = input;
}

#[test]
fn package_01_pypi_normalization_pypi_mixed_underscores_and_case() {
    // Fixture: package/01_pypi_normalization.json | Case: "pypi mixed underscores and case"
    let input: Value = serde_json::from_str(r#"{"ecosystem":"pypi","name":"My_Cool_Package"}"#)
        .expect("parse input");
    let expected: Value =
        serde_json::from_str(r#"{"normalized":"my-cool-package"}"#).expect("parse expected");
    // This test case expects success.
    assert!(
        expected.is_object(),
        "expected must be a JSON object: {}",
        "pypi mixed underscores and case"
    );
    assert!(
        !expected.as_object().unwrap().is_empty(),
        "expected must not be empty for success case: {}",
        "pypi mixed underscores and case"
    );
    let _ = input;
}

#[test]
fn package_01_pypi_normalization_pypi_already_normalized() {
    // Fixture: package/01_pypi_normalization.json | Case: "pypi already normalized"
    let input: Value =
        serde_json::from_str(r#"{"ecosystem":"pypi","name":"requests"}"#).expect("parse input");
    let expected: Value =
        serde_json::from_str(r#"{"normalized":"requests"}"#).expect("parse expected");
    // This test case expects success.
    assert!(
        expected.is_object(),
        "expected must be a JSON object: {}",
        "pypi already normalized"
    );
    assert!(
        !expected.as_object().unwrap().is_empty(),
        "expected must not be empty for success case: {}",
        "pypi already normalized"
    );
    let _ = input;
}

#[test]
fn package_01_pypi_normalization_npm_passthrough() {
    // Fixture: package/01_pypi_normalization.json | Case: "npm passthrough"
    let input: Value =
        serde_json::from_str(r#"{"ecosystem":"npm","name":"lodash"}"#).expect("parse input");
    let expected: Value =
        serde_json::from_str(r#"{"normalized":"lodash"}"#).expect("parse expected");
    // This test case expects success.
    assert!(
        expected.is_object(),
        "expected must be a JSON object: {}",
        "npm passthrough"
    );
    assert!(
        !expected.as_object().unwrap().is_empty(),
        "expected must not be empty for success case: {}",
        "npm passthrough"
    );
    let _ = input;
}

#[test]
fn package_01_pypi_normalization_npm_scoped_package() {
    // Fixture: package/01_pypi_normalization.json | Case: "npm scoped package"
    let input: Value =
        serde_json::from_str(r#"{"ecosystem":"npm","name":"@types/node"}"#).expect("parse input");
    let expected: Value =
        serde_json::from_str(r#"{"normalized":"@types/node"}"#).expect("parse expected");
    // This test case expects success.
    assert!(
        expected.is_object(),
        "expected must be a JSON object: {}",
        "npm scoped package"
    );
    assert!(
        !expected.as_object().unwrap().is_empty(),
        "expected must not be empty for success case: {}",
        "npm scoped package"
    );
    let _ = input;
}

#[test]
fn package_01_pypi_normalization_cargo_lowercase() {
    // Fixture: package/01_pypi_normalization.json | Case: "cargo lowercase"
    let input: Value =
        serde_json::from_str(r#"{"ecosystem":"cargo","name":"Serde"}"#).expect("parse input");
    let expected: Value =
        serde_json::from_str(r#"{"normalized":"serde"}"#).expect("parse expected");
    // This test case expects success.
    assert!(
        expected.is_object(),
        "expected must be a JSON object: {}",
        "cargo lowercase"
    );
    assert!(
        !expected.as_object().unwrap().is_empty(),
        "expected must not be empty for success case: {}",
        "cargo lowercase"
    );
    let _ = input;
}

#[test]
fn package_01_pypi_normalization_cargo_underscore_preserved() {
    // Fixture: package/01_pypi_normalization.json | Case: "cargo underscore preserved"
    let input: Value =
        serde_json::from_str(r#"{"ecosystem":"cargo","name":"serde_json"}"#).expect("parse input");
    let expected: Value =
        serde_json::from_str(r#"{"normalized":"serde_json"}"#).expect("parse expected");
    // This test case expects success.
    assert!(
        expected.is_object(),
        "expected must be a JSON object: {}",
        "cargo underscore preserved"
    );
    assert!(
        !expected.as_object().unwrap().is_empty(),
        "expected must not be empty for success case: {}",
        "cargo underscore preserved"
    );
    let _ = input;
}

#[test]
fn package_01_pypi_normalization_hex_lowercase() {
    // Fixture: package/01_pypi_normalization.json | Case: "hex lowercase"
    let input: Value =
        serde_json::from_str(r#"{"ecosystem":"hex","name":"Phoenix"}"#).expect("parse input");
    let expected: Value =
        serde_json::from_str(r#"{"normalized":"phoenix"}"#).expect("parse expected");
    // This test case expects success.
    assert!(
        expected.is_object(),
        "expected must be a JSON object: {}",
        "hex lowercase"
    );
    assert!(
        !expected.as_object().unwrap().is_empty(),
        "expected must not be empty for success case: {}",
        "hex lowercase"
    );
    let _ = input;
}

// Fixture: package/02_storage_keys.json
#[test]
fn package_02_storage_keys_pypi_storage_key() {
    // Fixture: package/02_storage_keys.json | Case: "pypi storage key"
    let input: Value = serde_json::from_str(r#"{"ecosystem":"pypi","filename":"requests-2.31.0.tar.gz","name":"requests","version":"2.31.0"}"#).expect("parse input");
    let expected: Value =
        serde_json::from_str(r#"{"key":"pypi/requests/2.31.0/requests-2.31.0.tar.gz"}"#)
            .expect("parse expected");
    // This test case expects success.
    assert!(
        expected.is_object(),
        "expected must be a JSON object: {}",
        "pypi storage key"
    );
    assert!(
        !expected.as_object().unwrap().is_empty(),
        "expected must not be empty for success case: {}",
        "pypi storage key"
    );
    let _ = input;
}

#[test]
fn package_02_storage_keys_npm_storage_key() {
    // Fixture: package/02_storage_keys.json | Case: "npm storage key"
    let input: Value = serde_json::from_str(r#"{"ecosystem":"npm","filename":"lodash-4.17.21.tgz","name":"lodash","version":"4.17.21"}"#).expect("parse input");
    let expected: Value =
        serde_json::from_str(r#"{"key":"npm/lodash/4.17.21/lodash-4.17.21.tgz"}"#)
            .expect("parse expected");
    // This test case expects success.
    assert!(
        expected.is_object(),
        "expected must be a JSON object: {}",
        "npm storage key"
    );
    assert!(
        !expected.as_object().unwrap().is_empty(),
        "expected must not be empty for success case: {}",
        "npm storage key"
    );
    let _ = input;
}

#[test]
fn package_02_storage_keys_cargo_storage_key() {
    // Fixture: package/02_storage_keys.json | Case: "cargo storage key"
    let input: Value = serde_json::from_str(r#"{"ecosystem":"cargo","filename":"serde-1.0.200.crate","name":"serde","version":"1.0.200"}"#).expect("parse input");
    let expected: Value =
        serde_json::from_str(r#"{"key":"cargo/serde/1.0.200/serde-1.0.200.crate"}"#)
            .expect("parse expected");
    // This test case expects success.
    assert!(
        expected.is_object(),
        "expected must be a JSON object: {}",
        "cargo storage key"
    );
    assert!(
        !expected.as_object().unwrap().is_empty(),
        "expected must not be empty for success case: {}",
        "cargo storage key"
    );
    let _ = input;
}

#[test]
fn package_02_storage_keys_hex_storage_key() {
    // Fixture: package/02_storage_keys.json | Case: "hex storage key"
    let input: Value = serde_json::from_str(r#"{"ecosystem":"hex","filename":"phoenix-1.7.12.tar","name":"phoenix","version":"1.7.12"}"#).expect("parse input");
    let expected: Value =
        serde_json::from_str(r#"{"key":"hex/phoenix/1.7.12/phoenix-1.7.12.tar"}"#)
            .expect("parse expected");
    // This test case expects success.
    assert!(
        expected.is_object(),
        "expected must be a JSON object: {}",
        "hex storage key"
    );
    assert!(
        !expected.as_object().unwrap().is_empty(),
        "expected must not be empty for success case: {}",
        "hex storage key"
    );
    let _ = input;
}

// Fixture: package/03_ecosystem_parsing.json
#[test]
fn package_03_ecosystem_parsing_pypi_lowercase() {
    // Fixture: package/03_ecosystem_parsing.json | Case: "pypi lowercase"
    let input: Value = serde_json::from_str(r#"{"value":"pypi"}"#).expect("parse input");
    let expected: Value = serde_json::from_str(r#"{"ecosystem":"pypi"}"#).expect("parse expected");
    // This test case expects success.
    assert!(
        expected.is_object(),
        "expected must be a JSON object: {}",
        "pypi lowercase"
    );
    assert!(
        !expected.as_object().unwrap().is_empty(),
        "expected must not be empty for success case: {}",
        "pypi lowercase"
    );
    let _ = input;
}

#[test]
fn package_03_ecosystem_parsing_pypi_uppercase() {
    // Fixture: package/03_ecosystem_parsing.json | Case: "pypi uppercase"
    let input: Value = serde_json::from_str(r#"{"value":"PYPI"}"#).expect("parse input");
    let expected: Value = serde_json::from_str(r#"{"ecosystem":"pypi"}"#).expect("parse expected");
    // This test case expects success.
    assert!(
        expected.is_object(),
        "expected must be a JSON object: {}",
        "pypi uppercase"
    );
    assert!(
        !expected.as_object().unwrap().is_empty(),
        "expected must not be empty for success case: {}",
        "pypi uppercase"
    );
    let _ = input;
}

#[test]
fn package_03_ecosystem_parsing_pypi_mixed_case() {
    // Fixture: package/03_ecosystem_parsing.json | Case: "pypi mixed case"
    let input: Value = serde_json::from_str(r#"{"value":"PyPI"}"#).expect("parse input");
    let expected: Value = serde_json::from_str(r#"{"ecosystem":"pypi"}"#).expect("parse expected");
    // This test case expects success.
    assert!(
        expected.is_object(),
        "expected must be a JSON object: {}",
        "pypi mixed case"
    );
    assert!(
        !expected.as_object().unwrap().is_empty(),
        "expected must not be empty for success case: {}",
        "pypi mixed case"
    );
    let _ = input;
}

#[test]
fn package_03_ecosystem_parsing_npm_lowercase() {
    // Fixture: package/03_ecosystem_parsing.json | Case: "npm lowercase"
    let input: Value = serde_json::from_str(r#"{"value":"npm"}"#).expect("parse input");
    let expected: Value = serde_json::from_str(r#"{"ecosystem":"npm"}"#).expect("parse expected");
    // This test case expects success.
    assert!(
        expected.is_object(),
        "expected must be a JSON object: {}",
        "npm lowercase"
    );
    assert!(
        !expected.as_object().unwrap().is_empty(),
        "expected must not be empty for success case: {}",
        "npm lowercase"
    );
    let _ = input;
}

#[test]
fn package_03_ecosystem_parsing_npm_uppercase() {
    // Fixture: package/03_ecosystem_parsing.json | Case: "npm uppercase"
    let input: Value = serde_json::from_str(r#"{"value":"NPM"}"#).expect("parse input");
    let expected: Value = serde_json::from_str(r#"{"ecosystem":"npm"}"#).expect("parse expected");
    // This test case expects success.
    assert!(
        expected.is_object(),
        "expected must be a JSON object: {}",
        "npm uppercase"
    );
    assert!(
        !expected.as_object().unwrap().is_empty(),
        "expected must not be empty for success case: {}",
        "npm uppercase"
    );
    let _ = input;
}

#[test]
fn package_03_ecosystem_parsing_cargo_lowercase() {
    // Fixture: package/03_ecosystem_parsing.json | Case: "cargo lowercase"
    let input: Value = serde_json::from_str(r#"{"value":"cargo"}"#).expect("parse input");
    let expected: Value = serde_json::from_str(r#"{"ecosystem":"cargo"}"#).expect("parse expected");
    // This test case expects success.
    assert!(
        expected.is_object(),
        "expected must be a JSON object: {}",
        "cargo lowercase"
    );
    assert!(
        !expected.as_object().unwrap().is_empty(),
        "expected must not be empty for success case: {}",
        "cargo lowercase"
    );
    let _ = input;
}

#[test]
fn package_03_ecosystem_parsing_crates_alias() {
    // Fixture: package/03_ecosystem_parsing.json | Case: "crates alias"
    let input: Value = serde_json::from_str(r#"{"value":"crates"}"#).expect("parse input");
    let expected: Value = serde_json::from_str(r#"{"ecosystem":"cargo"}"#).expect("parse expected");
    // This test case expects success.
    assert!(
        expected.is_object(),
        "expected must be a JSON object: {}",
        "crates alias"
    );
    assert!(
        !expected.as_object().unwrap().is_empty(),
        "expected must not be empty for success case: {}",
        "crates alias"
    );
    let _ = input;
}

#[test]
fn package_03_ecosystem_parsing_crates_uppercase_alias() {
    // Fixture: package/03_ecosystem_parsing.json | Case: "crates uppercase alias"
    let input: Value = serde_json::from_str(r#"{"value":"CRATES"}"#).expect("parse input");
    let expected: Value = serde_json::from_str(r#"{"ecosystem":"cargo"}"#).expect("parse expected");
    // This test case expects success.
    assert!(
        expected.is_object(),
        "expected must be a JSON object: {}",
        "crates uppercase alias"
    );
    assert!(
        !expected.as_object().unwrap().is_empty(),
        "expected must not be empty for success case: {}",
        "crates uppercase alias"
    );
    let _ = input;
}

#[test]
fn package_03_ecosystem_parsing_hex_lowercase() {
    // Fixture: package/03_ecosystem_parsing.json | Case: "hex lowercase"
    let input: Value = serde_json::from_str(r#"{"value":"hex"}"#).expect("parse input");
    let expected: Value = serde_json::from_str(r#"{"ecosystem":"hex"}"#).expect("parse expected");
    // This test case expects success.
    assert!(
        expected.is_object(),
        "expected must be a JSON object: {}",
        "hex lowercase"
    );
    assert!(
        !expected.as_object().unwrap().is_empty(),
        "expected must not be empty for success case: {}",
        "hex lowercase"
    );
    let _ = input;
}

#[test]
fn package_03_ecosystem_parsing_hex_uppercase() {
    // Fixture: package/03_ecosystem_parsing.json | Case: "hex uppercase"
    let input: Value = serde_json::from_str(r#"{"value":"HEX"}"#).expect("parse input");
    let expected: Value = serde_json::from_str(r#"{"ecosystem":"hex"}"#).expect("parse expected");
    // This test case expects success.
    assert!(
        expected.is_object(),
        "expected must be a JSON object: {}",
        "hex uppercase"
    );
    assert!(
        !expected.as_object().unwrap().is_empty(),
        "expected must not be empty for success case: {}",
        "hex uppercase"
    );
    let _ = input;
}

#[test]
fn package_03_ecosystem_parsing_unknown_ecosystem() {
    // Fixture: package/03_ecosystem_parsing.json | Case: "unknown ecosystem"
    let input: Value = serde_json::from_str(r#"{"value":"maven"}"#).expect("parse input");
    let expected: Value = serde_json::from_str(r#"{}"#).expect("parse expected");
    let error_substring = "unknown ecosystem";
    // This test case expects an error.
    assert!(
        !expected.as_object().is_some_and(|obj| obj.is_empty()) || !error_substring.is_empty(),
        "error case must have non-empty error substring or non-empty expected: {} ({})",
        error_substring,
        "unknown ecosystem"
    );
    // Verify fixture is loadable and error field is present.
    assert!(
        !error_substring.is_empty(),
        "error substring should not be empty for error case: {}",
        "unknown ecosystem"
    );
    let _ = (input, expected);
}

#[test]
fn package_03_ecosystem_parsing_empty_string() {
    // Fixture: package/03_ecosystem_parsing.json | Case: "empty string"
    let input: Value = serde_json::from_str(r#"{"value":""}"#).expect("parse input");
    let expected: Value = serde_json::from_str(r#"{}"#).expect("parse expected");
    let error_substring = "unknown ecosystem";
    // This test case expects an error.
    assert!(
        !expected.as_object().is_some_and(|obj| obj.is_empty()) || !error_substring.is_empty(),
        "error case must have non-empty error substring or non-empty expected: {} ({})",
        error_substring,
        "empty string"
    );
    // Verify fixture is loadable and error field is present.
    assert!(
        !error_substring.is_empty(),
        "error substring should not be empty for error case: {}",
        "empty string"
    );
    let _ = (input, expected);
}

#[test]
fn package_03_ecosystem_parsing_numeric_input() {
    // Fixture: package/03_ecosystem_parsing.json | Case: "numeric input"
    let input: Value = serde_json::from_str(r#"{"value":"123"}"#).expect("parse input");
    let expected: Value = serde_json::from_str(r#"{}"#).expect("parse expected");
    let error_substring = "unknown ecosystem";
    // This test case expects an error.
    assert!(
        !expected.as_object().is_some_and(|obj| obj.is_empty()) || !error_substring.is_empty(),
        "error case must have non-empty error substring or non-empty expected: {} ({})",
        error_substring,
        "numeric input"
    );
    // Verify fixture is loadable and error field is present.
    assert!(
        !error_substring.is_empty(),
        "error substring should not be empty for error case: {}",
        "numeric input"
    );
    let _ = (input, expected);
}

// Fixture: policy/01_policy_checks.json
#[test]
fn policy_01_policy_checks_allow_everything_by_default() {
    // Fixture: policy/01_policy_checks.json | Case: "allow everything by default"
    let input: Value = serde_json::from_str(r#"{"package":{"license":"Apache-2.0","name":"requests","version":"2.31.0","yanked":false},"policy":{}}"#).expect("parse input");
    let expected: Value = serde_json::from_str(r#"{"allowed":true}"#).expect("parse expected");
    // This test case expects success.
    assert!(
        expected.is_object(),
        "expected must be a JSON object: {}",
        "allow everything by default"
    );
    assert!(
        !expected.as_object().unwrap().is_empty(),
        "expected must not be empty for success case: {}",
        "allow everything by default"
    );
    let _ = input;
}

#[test]
fn policy_01_policy_checks_block_explicitly_blocked_package() {
    // Fixture: policy/01_policy_checks.json | Case: "block explicitly blocked package"
    let input: Value = serde_json::from_str(r#"{"package":{"license":"MIT","name":"malware-pkg","version":"1.0.0","yanked":false},"policy":{"blocked_packages":["malware-pkg"]}}"#).expect("parse input");
    let expected: Value = serde_json::from_str(r#"{"allowed":false}"#).expect("parse expected");
    let error_substring = "malware-pkg is blocked";
    // This test case expects an error.
    assert!(
        !expected.as_object().is_some_and(|obj| obj.is_empty()) || !error_substring.is_empty(),
        "error case must have non-empty error substring or non-empty expected: {} ({})",
        error_substring,
        "block explicitly blocked package"
    );
    // Verify fixture is loadable and error field is present.
    assert!(
        !error_substring.is_empty(),
        "error substring should not be empty for error case: {}",
        "block explicitly blocked package"
    );
    let _ = (input, expected);
}

#[test]
fn policy_01_policy_checks_block_unlicensed_when_configured() {
    // Fixture: policy/01_policy_checks.json | Case: "block unlicensed when configured"
    let input: Value = serde_json::from_str(r#"{"package":{"license":null,"name":"no-license","version":"0.1.0","yanked":false},"policy":{"block_unlicensed":true}}"#).expect("parse input");
    let expected: Value = serde_json::from_str(r#"{"allowed":false}"#).expect("parse expected");
    let error_substring = "no license";
    // This test case expects an error.
    assert!(
        !expected.as_object().is_some_and(|obj| obj.is_empty()) || !error_substring.is_empty(),
        "error case must have non-empty error substring or non-empty expected: {} ({})",
        error_substring,
        "block unlicensed when configured"
    );
    // Verify fixture is loadable and error field is present.
    assert!(
        !error_substring.is_empty(),
        "error substring should not be empty for error case: {}",
        "block unlicensed when configured"
    );
    let _ = (input, expected);
}

#[test]
fn policy_01_policy_checks_allow_unlicensed_when_not_configured() {
    // Fixture: policy/01_policy_checks.json | Case: "allow unlicensed when not configured"
    let input: Value = serde_json::from_str(r#"{"package":{"license":null,"name":"no-license","version":"0.1.0","yanked":false},"policy":{"block_unlicensed":false}}"#).expect("parse input");
    let expected: Value = serde_json::from_str(r#"{"allowed":true}"#).expect("parse expected");
    // This test case expects success.
    assert!(
        expected.is_object(),
        "expected must be a JSON object: {}",
        "allow unlicensed when not configured"
    );
    assert!(
        !expected.as_object().unwrap().is_empty(),
        "expected must not be empty for success case: {}",
        "allow unlicensed when not configured"
    );
    let _ = input;
}

#[test]
fn policy_01_policy_checks_block_license_not_in_allowlist() {
    // Fixture: policy/01_policy_checks.json | Case: "block license not in allowlist"
    let input: Value = serde_json::from_str(r#"{"package":{"license":"GPL-3.0","name":"gpl-pkg","version":"1.0.0","yanked":false},"policy":{"allowed_licenses":["MIT","Apache-2.0"]}}"#).expect("parse input");
    let expected: Value = serde_json::from_str(r#"{"allowed":false}"#).expect("parse expected");
    let error_substring = "not in allowed list";
    // This test case expects an error.
    assert!(
        !expected.as_object().is_some_and(|obj| obj.is_empty()) || !error_substring.is_empty(),
        "error case must have non-empty error substring or non-empty expected: {} ({})",
        error_substring,
        "block license not in allowlist"
    );
    // Verify fixture is loadable and error field is present.
    assert!(
        !error_substring.is_empty(),
        "error substring should not be empty for error case: {}",
        "block license not in allowlist"
    );
    let _ = (input, expected);
}

#[test]
fn policy_01_policy_checks_allow_license_in_allowlist() {
    // Fixture: policy/01_policy_checks.json | Case: "allow license in allowlist"
    let input: Value = serde_json::from_str(r#"{"package":{"license":"MIT","name":"good-pkg","version":"1.0.0","yanked":false},"policy":{"allowed_licenses":["MIT","Apache-2.0"]}}"#).expect("parse input");
    let expected: Value = serde_json::from_str(r#"{"allowed":true}"#).expect("parse expected");
    // This test case expects success.
    assert!(
        expected.is_object(),
        "expected must be a JSON object: {}",
        "allow license in allowlist"
    );
    assert!(
        !expected.as_object().unwrap().is_empty(),
        "expected must not be empty for success case: {}",
        "allow license in allowlist"
    );
    let _ = input;
}

#[test]
fn policy_01_policy_checks_empty_allowlist_allows_all_licenses() {
    // Fixture: policy/01_policy_checks.json | Case: "empty allowlist allows all licenses"
    let input: Value = serde_json::from_str(r#"{"package":{"license":"WTFPL","name":"any-pkg","version":"1.0.0","yanked":false},"policy":{"allowed_licenses":[]}}"#).expect("parse input");
    let expected: Value = serde_json::from_str(r#"{"allowed":true}"#).expect("parse expected");
    // This test case expects success.
    assert!(
        expected.is_object(),
        "expected must be a JSON object: {}",
        "empty allowlist allows all licenses"
    );
    assert!(
        !expected.as_object().unwrap().is_empty(),
        "expected must not be empty for success case: {}",
        "empty allowlist allows all licenses"
    );
    let _ = input;
}

#[test]
fn policy_01_policy_checks_non_blocked_package_passes() {
    // Fixture: policy/01_policy_checks.json | Case: "non-blocked package passes"
    let input: Value = serde_json::from_str(r#"{"package":{"license":"MIT","name":"good-pkg","version":"1.0.0","yanked":false},"policy":{"blocked_packages":["other-pkg"]}}"#).expect("parse input");
    let expected: Value = serde_json::from_str(r#"{"allowed":true}"#).expect("parse expected");
    // This test case expects success.
    assert!(
        expected.is_object(),
        "expected must be a JSON object: {}",
        "non-blocked package passes"
    );
    assert!(
        !expected.as_object().unwrap().is_empty(),
        "expected must not be empty for success case: {}",
        "non-blocked package passes"
    );
    let _ = input;
}
