use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use clap::Parser;
use serde::Deserialize;

/// Generates Rust integration test code from JSON fixture files.
///
/// Walks a directory of JSON fixture files conforming to the depot fixture
/// schema and produces a single Rust source file containing `#[test]`
/// functions for each test case.
#[derive(Parser)]
#[command(
    name = "depot-test-generator",
    about = "Generate tests from JSON fixtures"
)]
struct Cli {
    /// Path to the directory containing JSON fixture files
    #[arg(long)]
    fixtures: PathBuf,

    /// Path to the output Rust test file
    #[arg(long)]
    output: PathBuf,
}

/// A single test case inside a fixture file.
#[derive(Debug, Deserialize)]
struct TestCase {
    name: String,
    #[allow(dead_code)]
    description: Option<String>,
    input: serde_json::Value,
    expected: serde_json::Value,
    error: Option<String>,
}

fn main() {
    let cli = Cli::parse();

    let fixture_files = collect_fixture_files(&cli.fixtures);
    if fixture_files.is_empty() {
        eprintln!(
            "warning: no JSON fixture files found in {}",
            cli.fixtures.display()
        );
    }

    let mut output = String::new();
    writeln!(
        output,
        "// Auto-generated by depot-test-generator. Do not edit manually."
    )
    .unwrap();
    writeln!(output, "// Source fixtures: {}", cli.fixtures.display()).unwrap();
    writeln!(output).unwrap();
    writeln!(output, "use serde_json::Value;").unwrap();
    writeln!(output).unwrap();

    let mut total_tests = 0usize;

    for fixture_path in &fixture_files {
        let relative = fixture_path
            .strip_prefix(&cli.fixtures)
            .unwrap_or(fixture_path);

        let content = match std::fs::read_to_string(fixture_path) {
            Ok(content) => content,
            Err(err) => {
                eprintln!("error: failed to read {}: {err}", fixture_path.display());
                std::process::exit(1);
            }
        };

        let cases: Vec<TestCase> = match serde_json::from_str(&content) {
            Ok(cases) => cases,
            Err(err) => {
                eprintln!("error: failed to parse {}: {err}", fixture_path.display());
                std::process::exit(1);
            }
        };

        // Derive a module-level prefix from the fixture path.
        let module_prefix = derive_module_prefix(relative);

        writeln!(output, "// Fixture: {}", relative.display()).unwrap();

        for case in &cases {
            let function_name = make_function_name(&module_prefix, &case.name);
            generate_test_function(&mut output, &function_name, case, relative);
            total_tests += 1;
        }

        writeln!(output).unwrap();
    }

    if let Some(parent) = cli.output.parent()
        && !parent.exists()
    {
        std::fs::create_dir_all(parent).unwrap_or_else(|err| {
            eprintln!(
                "error: failed to create directory {}: {err}",
                parent.display()
            );
            std::process::exit(1);
        });
    }

    std::fs::write(&cli.output, &output).unwrap_or_else(|err| {
        eprintln!("error: failed to write {}: {err}", cli.output.display());
        std::process::exit(1);
    });

    eprintln!(
        "generated {total_tests} test(s) from {} fixture file(s) -> {}",
        fixture_files.len(),
        cli.output.display()
    );
}

/// Collects all `.json` files under `directory`, excluding the schema file,
/// sorted by path for deterministic output.
fn collect_fixture_files(directory: &Path) -> Vec<PathBuf> {
    let mut files: Vec<PathBuf> = walkdir::WalkDir::new(directory)
        .sort_by_file_name()
        .into_iter()
        .filter_map(|entry| entry.ok())
        .filter(|entry| entry.file_type().is_file())
        .filter(|entry| entry.path().extension().is_some_and(|ext| ext == "json"))
        .filter(|entry| {
            // Skip the schema file itself.
            !entry
                .file_name()
                .to_str()
                .is_some_and(|name| name.starts_with("00-"))
        })
        .map(|entry| entry.into_path())
        .collect();

    files.sort();
    files
}

/// Derives a module prefix from the fixture's relative path.
///
/// For example, `config/01_config_parsing.json` becomes `config_01_config_parsing`.
fn derive_module_prefix(relative_path: &Path) -> String {
    let stem = relative_path.with_extension("");
    let raw = stem
        .to_string_lossy()
        .replace(['/', '\\'], "_")
        .replace('-', "_");
    sanitize_identifier(&raw)
}

/// Converts a test case name into a valid Rust function name.
fn make_function_name(prefix: &str, case_name: &str) -> String {
    let suffix = case_name
        .to_lowercase()
        .replace(|c: char| !c.is_alphanumeric() && c != '_', "_")
        .replace("__", "_")
        .trim_matches('_')
        .to_string();

    let raw = format!("{prefix}_{suffix}");
    sanitize_identifier(&raw)
}

/// Ensures the string is a valid Rust identifier.
fn sanitize_identifier(input: &str) -> String {
    let mut result: String = input
        .chars()
        .map(|c| {
            if c.is_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect();

    // Collapse consecutive underscores.
    while result.contains("__") {
        result = result.replace("__", "_");
    }

    // Strip leading/trailing underscores.
    result = result.trim_matches('_').to_string();

    // Prefix with underscore if it starts with a digit.
    if result.starts_with(|c: char| c.is_ascii_digit()) {
        result = format!("_{result}");
    }

    // Fallback for empty.
    if result.is_empty() {
        result = "unnamed_test".to_string();
    }

    result
}

/// Generates a single `#[test]` function for a test case.
fn generate_test_function(
    output: &mut String,
    function_name: &str,
    case: &TestCase,
    fixture_path: &Path,
) {
    let input_json = serde_json::to_string(&case.input).unwrap();
    let expected_json = serde_json::to_string(&case.expected).unwrap();

    writeln!(output, "#[test]").unwrap();
    writeln!(output, "fn {function_name}() {{").unwrap();
    writeln!(
        output,
        "    // Fixture: {} | Case: {:?}",
        fixture_path.display(),
        case.name
    )
    .unwrap();
    writeln!(
        output,
        "    let input: Value = serde_json::from_str(r#\"{}\"#).expect(\"parse input\");",
        escape_raw_string(&input_json)
    )
    .unwrap();
    writeln!(
        output,
        "    let expected: Value = serde_json::from_str(r#\"{}\"#).expect(\"parse expected\");",
        escape_raw_string(&expected_json)
    )
    .unwrap();

    match &case.error {
        Some(error_substring) => {
            writeln!(output, "    let error_substring = {:?};", error_substring).unwrap();
            writeln!(output, "    // This test case expects an error.").unwrap();
            writeln!(output, "    assert!(").unwrap();
            writeln!(
                output,
                "        !expected.as_object().map_or(false, |obj| obj.is_empty())  || !error_substring.is_empty(),"
            )
            .unwrap();
            writeln!(
                output,
                "        \"error case must have non-empty error substring or non-empty expected: {{}} ({{}})\",",
            )
            .unwrap();
            writeln!(output, "        error_substring, {:?}", case.name,).unwrap();
            writeln!(output, "    );").unwrap();
            writeln!(
                output,
                "    // Verify fixture is loadable and error field is present."
            )
            .unwrap();
            writeln!(
                output,
                "    assert!(!error_substring.is_empty(), \"error substring should not be empty for error case: {{}}\", {:?});",
                case.name,
            )
            .unwrap();
            writeln!(output, "    let _ = (input, expected);").unwrap();
        }
        None => {
            writeln!(output, "    // This test case expects success.").unwrap();
            writeln!(
                output,
                "    assert!(expected.is_object(), \"expected must be a JSON object: {{}}\", {:?});",
                case.name,
            )
            .unwrap();
            writeln!(
                output,
                "    assert!(!expected.as_object().unwrap().is_empty(), \"expected must not be empty for success case: {{}}\", {:?});",
                case.name,
            )
            .unwrap();
            writeln!(output, "    let _ = input;").unwrap();
        }
    }

    writeln!(output, "}}").unwrap();
    writeln!(output).unwrap();
}

/// Escapes content that could break a `r#"..."#` raw string literal.
///
/// The only problematic sequence is `"#` — we replace it with `\"#` inside
/// the raw string, which is imperfect but sufficient for JSON values that
/// do not contain that sequence.
fn escape_raw_string(input: &str) -> String {
    input.replace("\"#", "\\\"#")
}
